Disable check libs label
canonical/mysql-router-operator pull request #35
Opened 2023-03-29 18:38 UTC by carlcsaposs-canonical

Ported from https://github.com/canonical/mysql-operator/pull/165

2023-03-29 18:43 UTC, shayancanonical approved these changes

2023-03-29 18:50 UTC, taurus-forever commented
Please check my comment in https://github.com/canonical/mysql-operator/pull/165#issuecomment-1489127957 before merging.

2023-03-29 19:19 UTC, taurus-forever requested changes

2023-03-29 19:19 UTC, taurus-forever commented on .github/workflows/ci.yaml
> +          fail-build: true
${{ github.event_name == 'pull_request' }}

2023-03-30 09:50 UTC, taurus-forever approved these changes

2023-03-30 11:27 UTC, merged